### ISSUE TITLE
Any thoughts to have formatting output as STDOUT?

### ISSUE THREAD

**Issue by shmup** [weavejester/cljfmt#121]
I was going to toy around with improving [vim-cljfmt](https://github.com/venantius/vim-cljfmt) since it doesn't follow nice practices, and just runs _all the time_.

But really, that's not even what I prefer in vim. I really want to use vim's builtin `formatprg`, and set it to `cljfmt` for `ftdetect/clojure.vim`. Cool.

But that'd require that `cljfmt` itself has the option to just output the formatted code, and nothing extra. Possibly via some passed in argument.

Has this ever been thought about? Problems with the idea? Or just work that'd need to be done.

**Comment by weavejester** [comment]
`cljfmt.core/reformat-string` returns the formatted code as a string, so you can do whatever you want with it, including printing it to `STDOUT`.

**Comment by shmup** [comment]
Let me wrap my head around what would be needed for this. I assume it is trivial, but I'm new to this stack (language/tools), and am uncertain what the best way to call `lein cljfmt` but specifically `reformat-string`, is, conveniently.

**Comment by weavejester** [comment]
It depends what exactly you want to do. If you're running a binary, you may want to look into one of the versions of cljfmt compiled for node, as the startup time for that is better. Otherwise you'll want to construct some small program that takes whatever input `formatprg` expects, and produces the right output by piping the input through `reformat-string`.

**Comment by shmup** [comment]
But one of the binaries compiled for node just updates the file in place it appears, no stdout? So I'd still be interested in `reformat-string` it appears?
