### ISSUE TITLE
Indentation lost after comment line

### ISSUE THREAD

**Issue by weissjeffm** [weavejester/cljfmt#82]
When a line is commented out and what's next is `]`, then that gets aligned at column 1 for some reason. It should be at column 4, i believe (that's what clojure-mode does).

Input for cljfmt fix:

``` clj
(let [x y]
  [this
   that
   ;;other
   ]
  )
```

output

``` clj
(let [x y]
  [this
   that
   ;;other
])
```

expected

``` clj
(let [x y]
  [this
   that
   ;;other
   ])
```

**Comment by weissjeffm** [comment]
BTW the same thing happens inside a map literal also.

**Comment by arrdem** [comment]
So I think what's happening here is that the comment is messing up scanning backwards to the previous form to get indentation... definitely a bug in cljfmt not rewrite-clj and shouldn't be too hard to fix.

**Comment by MatthewDarling** [comment]
Stepping through with the CIDER debugger, [`remove-surrounding-whitespace`](https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/core.cljc#L58) is responsible. The whitespace disappears after a few iterations through `edit-all`.

When it looks at the whitespace starting the line after `;;;test1`, `surrounding-whitespace?` returns true, because the current node is whitespace and [part of this `or` is returning true](https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/core.cljc#L48).

I guess we'd want to modify that conditional on line 48 to fix the issue? I'm not sure I understand enough to do that, so far.

**Comment by MatthewDarling** [comment]
Starting to understand `rewrite-clj` and `cljfmt` a bit better, so I took another look at this today.

## Slightly more informed description of the issue 

In terms of why `remove-surrounding-whitespace` is responsible: the README example is turning `( foo )` into `(foo)`. So `surrounding-whitespace?` check if a node is whitespace, and that it either has nothing to its left, or nothing but whitespace to its right.

Code like this triggers the "nothing but whitespace to the right" case (`<>` denotes the current node):

```clojure
(let [x y]
  [this
   that
   ;;other
<   >]
  )
```

There are no nodes to the right of that, so the whitespace node is removed under the assumption it's a `(foo )` situation.

## A possible fix

To distinguish between the two, we could check if the previous node is a comment, and only remove if it isn't:

```clojure
(defn- surrounding? [zloc p?]
  (and (p? zloc)
       (or (nil? (zip/left zloc))
           (and (nil? (skip zip/right p? zloc))
                (-> zloc zip/prev z/node n/comment? not)))))
```

And this does help: `surrounding-whitespace?` no longer returns true for the relevant cases.

## But wait, there's more

If our whitespace-after-a-comment passes unscathed through `remove-surrounding-whitespace`, it's culled by `unindent`, which removes all existing indentation with the intention of reinstating it via `indent`. However, `indent` doesn't know to return the whitespace in this case, since it doesn't really need to be there.

I've made a few attempts to fix this, but none of them pass all the existing tests + the one in #88. So it seems I'm stuck again. Happy to have help on this part!

**Comment by timmc-bcov** [comment]
That basically makes sense, but... if I set `:cljfmt { :remove-surrounding-whitespace? false }` the issue still occurs. So I wonder if that's really what's going on...

(Also, any recommendations on a workaround?)
