### ISSUE TITLE
Indent to 1 space, not 2 by default in several cases

### ISSUE THREAD

**Issue by razum2um** [weavejester/cljfmt#97]
You already mentioned here https://github.com/weavejester/cljfmt/issues/46#issuecomment-139166160 that there should be normally 2 spaces (I totally agree, and also idea+cursive formats code below this way by default). But default configuration of cljfmt does this:

```diff
 (some->
-  (foo)
-  (bar))
+ (foo)
+ (bar))

 (Thread.
-  #(baz))
+ #(baz))

 (bax
-  :x 1
-  :y 2)
+ :x 1
+ :y 2)
```

Reproduction repo: https://github.com/razum2um/cljfmt-space

**Comment by razum2um** [comment]
@weavejester configuration like this
```clj
:cljfmt {:indents ^:replace {#"some->" [[:inner 0]]
                             #"Thread\." [[:inner 0]]
                             #"bax" [[:inner 0]]}}

```
fixes behaviour, but obviously I cannot list every fn, and `#".*"` is not an option as well (break other things)

btw, @bbatsov I use spacemacs and it also formats the source with 1 space like above, why?

**Comment by weavejester** [comment]
This is [standard Clojure indentation](https://github.com/bbatsov/clojure-style-guide#one-space-indent). Unless the function is a macro with special indentation rules, this is how it should be indented.

**Comment by razum2um** [comment]
@weavejester thanks for such fast answer, ok, I probably should go to cursive's bugtracker then

**Comment by miridius** [comment]
> This is [standard Clojure indentation](https://github.com/bbatsov/clojure-style-guide#one-space-indent).

That style guide is unofficial, it is not a standards document, but rather a set of advice according to what the editors of the guide feel is best. There are several rules in there which are quite contentious and which often aren't followed in the wild. 1 space list indents is one of them. For example both IntelliJ Cursive and zprint don't follow this rule by default.

[The zprint docs specifically call out](https://cljdoc.org/d/zprint/zprint/1.2.8/doc/i-want-to-change-/the-configuration-to-track-the-community-standard#why-arent-the-community-standards-the-default) why it uses 2 space list indentation by default:

> * Treat "body" functions and "argument" function differently in the way that indentation is performed for these functions. In my explorations on GitHub, this is probably the least frequently followed of the community formatting standards.

While I personally the mixture of 1 space and 2 space indentation in functions/macros to be strange, I would be fine with it _if_ it could be standardised across all implementations and there was an agreed way to handle the various edge cases. The problem is that the rules are vague, the edge cases are many, and different formatters implement the edge cases differently to the point that no amount of configuration will make them agree. #45 is an example of this

In my experience the only way to have all editors and formatters agree is by using 2 space list indentation, so I would be very happy if that could be added as an option to `cljfmt`! I've tried using a wildcard indent rule, but unfortunately it doesn't work for the `:require` block inside `ns` - that still ends up with 1 space.

**Comment by weavejester** [comment]
> That style guide is unofficial, it is not a standards document

That is true, so let me correct myself. The single-space list indentation is the most common style of Clojure indentation in use, is the most common default for editors, and is the style chosen for the Clojure source code. Given this, it's also the most logical default for cljfmt.

That said, I have no objection at all to adding in options to support other styles of indentation, including the "constant 2-space" style. Please option a new issue for a feature request if this is what you want.

**Comment by miridius** [comment]
Thanks for the quick reply @weavejester!

I'm more than happy for one space to be the default. I'll open both a new issue and a PR for making it configurable :)
